from __future__ import annotations

from app.domain.models import BoardProfile


def _toolhead_profile(label: str, mcu: str) -> BoardProfile:
    return BoardProfile(
        label=label,
        mcu=mcu,
        serial_hint="canbus_uuid: replace-with-uuid",
        pins={
            "extruder_step": "toolhead:EXT_STEP",
            "extruder_dir": "toolhead:EXT_DIR",
            "extruder_enable": "toolhead:EXT_EN",
            "heater_hotend": "toolhead:HE0",
            "temp_hotend": "toolhead:TH0",
            "probe": "toolhead:PROBE",
            "toolhead_fan": "toolhead:FAN0",
            "part_cooling_fan": "toolhead:FAN1",
            "filament_sensor": "toolhead:FS0",
        },
        layout={
            "Motor and Heater": ["EXT_STEP", "EXT_DIR", "EXT_EN", "HE0"],
            "Sensors": ["TH0", "PROBE", "FS0"],
            "Fans and IO": ["FAN0", "FAN1", "RGB", "GPIO"],
        },
    )


BOARD_REGISTRY: dict[str, BoardProfile] = {
    "btt_octopus_1_1": BoardProfile(
        label="BTT Octopus 1.1",
        mcu="stm32f446xx",
        serial_hint="/dev/serial/by-id/usb-BTT_Octopus_11",
        pins={
            "stepper_x_step": "PB13",
            "stepper_x_dir": "PB12",
            "stepper_x_enable": "PB14",
            "stepper_y_step": "PB10",
            "stepper_y_dir": "PB2",
            "stepper_y_enable": "PB11",
            "stepper_z_step": "PE2",
            "stepper_z_dir": "PE3",
            "stepper_z_enable": "PE1",
            "extruder_step": "PE6",
            "extruder_dir": "PA14",
            "extruder_enable": "PE0",
            "heater_bed": "PA1",
            "heater_hotend": "PA2",
            "temp_bed": "PF3",
            "temp_hotend": "PF4",
            "probe": "PG15",
            "toolhead_fan": "PA8",
            "part_cooling_fan": "PA9",
            "filament_sensor": "PG12",
            "ams_step": "PG6",
            "ams_dir": "PG7",
            "ams_enable": "PG8",
        },
        layout={
            "Stepper Drivers": ["M0(X)", "M1(Y)", "M2(Z0)", "M3(Z1)", "M4(Z2)", "M5(E0)"],
            "Heaters": ["HE0", "HE1", "BED"],
            "Thermistors": ["T0", "T1", "TB"],
            "Control IO": ["PROBE", "ENDSTOP_X", "ENDSTOP_Y", "ENDSTOP_Z", "FAN0", "FAN1"],
        },
    ),
    "btt_octopus_pro_1_1": BoardProfile(
        label="BTT Octopus Pro 1.1",
        mcu="stm32f429xx",
        serial_hint="/dev/serial/by-id/usb-BTT_Octopus_Pro_11",
        pins={
            "stepper_x_step": "PF13",
            "stepper_x_dir": "PF12",
            "stepper_x_enable": "PF14",
            "stepper_y_step": "PG0",
            "stepper_y_dir": "PG1",
            "stepper_y_enable": "PF15",
            "stepper_z_step": "PE2",
            "stepper_z_dir": "PE3",
            "stepper_z_enable": "PE1",
            "extruder_step": "PE6",
            "extruder_dir": "PC13",
            "extruder_enable": "PE0",
            "heater_bed": "PA1",
            "heater_hotend": "PA2",
            "temp_bed": "PF3",
            "temp_hotend": "PF4",
            "probe": "PG15",
            "toolhead_fan": "PA8",
            "part_cooling_fan": "PA9",
            "filament_sensor": "PG12",
            "ams_step": "PG6",
            "ams_dir": "PG7",
            "ams_enable": "PG8",
        },
        layout={
            "Stepper Drivers": ["M0(X)", "M1(Y)", "M2(Z0)", "M3(Z1)", "M4(Z2)", "M5(E0)"],
            "Heaters": ["HE0", "HE1", "BED"],
            "Thermistors": ["T0", "T1", "TB"],
            "Expansion": ["EXP1", "EXP2", "CAN", "RGB"],
        },
    ),
    "manta_m8p_v2": BoardProfile(
        label="BTT Manta M8P V2",
        mcu="stm32g0b1xx",
        serial_hint="/dev/serial/by-id/usb-BTT_Manta_M8P_V2",
        pins={
            "stepper_x_step": "PC6",
            "stepper_x_dir": "PC7",
            "stepper_x_enable": "PD0",
            "stepper_y_step": "PC8",
            "stepper_y_dir": "PC9",
            "stepper_y_enable": "PD1",
            "stepper_z_step": "PA8",
            "stepper_z_dir": "PC5",
            "stepper_z_enable": "PA15",
            "extruder_step": "PE2",
            "extruder_dir": "PE3",
            "extruder_enable": "PE4",
            "heater_bed": "PB7",
            "heater_hotend": "PB8",
            "temp_bed": "PA0",
            "temp_hotend": "PA1",
            "probe": "PB6",
            "toolhead_fan": "PB9",
            "part_cooling_fan": "PB10",
            "filament_sensor": "PC14",
            "ams_step": "PD13",
            "ams_dir": "PD12",
            "ams_enable": "PD11",
        },
        layout={
            "Stepper Drivers": ["M0(X)", "M1(Y)", "M2(Z0)", "M3(Z1)", "M4(Z2)", "M5(E0)"],
            "Heaters": ["HE0", "HE1", "BED"],
            "Thermistors": ["TH0", "TH1", "THB"],
            "CAN and Expansion": ["CAN", "USB-C", "CB1 Header", "EXP1", "EXP2"],
        },
    ),
    "manta_m5p_v1_0": BoardProfile(
        label="BTT Manta M5P v1.0",
        mcu="stm32g0b1xx",
        serial_hint="/dev/serial/by-id/usb-BTT_Manta_M5P_V10",
        pins={
            "stepper_x_step": "PC6",
            "stepper_x_dir": "PC7",
            "stepper_x_enable": "PD0",
            "stepper_y_step": "PC8",
            "stepper_y_dir": "PC9",
            "stepper_y_enable": "PD1",
            "stepper_z_step": "PA8",
            "stepper_z_dir": "PC5",
            "stepper_z_enable": "PA15",
            "extruder_step": "PE2",
            "extruder_dir": "PE3",
            "extruder_enable": "PE4",
            "heater_bed": "PB7",
            "heater_hotend": "PB8",
            "temp_bed": "PA0",
            "temp_hotend": "PA1",
            "probe": "PB6",
            "toolhead_fan": "PB9",
            "part_cooling_fan": "PB10",
            "filament_sensor": "PC14",
            "ams_step": "PD13",
            "ams_dir": "PD12",
            "ams_enable": "PD11",
        },
        layout={
            "Stepper Drivers": ["M0(X)", "M1(Y)", "M2(Z0)", "M3(E0)", "M4(AUX)"],
            "Heaters": ["HE0", "HE1", "BED"],
            "Thermistors": ["TH0", "TH1", "THB"],
            "Expansion": ["CAN", "EXP1", "EXP2", "CB1 Header"],
        },
    ),
    "skr3_ez": BoardProfile(
        label="BTT SKR 3 EZ",
        mcu="stm32h743xx",
        serial_hint="/dev/serial/by-id/usb-BTT_SKR_3_EZ",
        pins={
            "stepper_x_step": "PF9",
            "stepper_x_dir": "PF10",
            "stepper_x_enable": "PF8",
            "stepper_y_step": "PC13",
            "stepper_y_dir": "PF0",
            "stepper_y_enable": "PC14",
            "stepper_z_step": "PE2",
            "stepper_z_dir": "PE3",
            "stepper_z_enable": "PE1",
            "extruder_step": "PD12",
            "extruder_dir": "PC4",
            "extruder_enable": "PE8",
            "heater_bed": "PD7",
            "heater_hotend": "PB3",
            "temp_bed": "PA1",
            "temp_hotend": "PA0",
            "probe": "PC2",
            "toolhead_fan": "PB7",
            "part_cooling_fan": "PB6",
            "filament_sensor": "PC15",
            "ams_step": "PE10",
            "ams_dir": "PE11",
            "ams_enable": "PE12",
        },
        layout={
            "Stepper Drivers": ["X", "Y", "Z", "E0", "E1"],
            "Heaters": ["HE0", "HE1", "BED"],
            "Thermistors": ["TH0", "TH1", "THB"],
            "Expansion": ["CAN", "UART", "EXP1", "EXP2"],
        },
    ),
    "btt_kraken": BoardProfile(
        label="BTT Kraken",
        mcu="stm32h723xx",
        serial_hint="/dev/serial/by-id/usb-BTT_Kraken",
        pins={
            "stepper_x_step": "PF13",
            "stepper_x_dir": "PF12",
            "stepper_x_enable": "PF14",
            "stepper_y_step": "PG0",
            "stepper_y_dir": "PG1",
            "stepper_y_enable": "PF15",
            "stepper_z_step": "PE2",
            "stepper_z_dir": "PE3",
            "stepper_z_enable": "PE1",
            "extruder_step": "PE6",
            "extruder_dir": "PC13",
            "extruder_enable": "PE0",
            "heater_bed": "PA1",
            "heater_hotend": "PA2",
            "temp_bed": "PF3",
            "temp_hotend": "PF4",
            "probe": "PG15",
            "toolhead_fan": "PA8",
            "part_cooling_fan": "PA9",
            "filament_sensor": "PG12",
            "ams_step": "PG6",
            "ams_dir": "PG7",
            "ams_enable": "PG8",
        },
        layout={
            "Stepper Drivers": ["M0", "M1", "M2", "M3", "M4", "M5", "M6", "M7"],
            "Heaters": ["HE0", "HE1", "HE2", "HE3", "BED"],
            "Thermistors": ["T0", "T1", "T2", "T3", "TB"],
            "Expansion": ["CAN", "USB-C", "EXP1", "EXP2", "RGB", "IO Bank"],
        },
    ),
    "fysetc_spider_v2": BoardProfile(
        label="FYSETC Spider V2",
        mcu="stm32f446xx",
        serial_hint="/dev/serial/by-id/usb-FYSETC_Spider_V2",
        pins={
            "stepper_x_step": "PE11",
            "stepper_x_dir": "PE10",
            "stepper_x_enable": "PE9",
            "stepper_y_step": "PD8",
            "stepper_y_dir": "PB12",
            "stepper_y_enable": "PD9",
            "stepper_z_step": "PD14",
            "stepper_z_dir": "PD13",
            "stepper_z_enable": "PD15",
            "extruder_step": "PE6",
            "extruder_dir": "PC13",
            "extruder_enable": "PE5",
            "heater_bed": "PB3",
            "heater_hotend": "PB4",
            "temp_bed": "PC0",
            "temp_hotend": "PC1",
            "probe": "PB5",
            "toolhead_fan": "PA8",
            "part_cooling_fan": "PA9",
            "filament_sensor": "PA10",
            "ams_step": "PC14",
            "ams_dir": "PC15",
            "ams_enable": "PD12",
        },
        layout={
            "Stepper Drivers": ["M0(X)", "M1(Y)", "M2(Z0)", "M3(Z1)", "M4(E0)", "M5(AUX)"],
            "Heaters": ["HE0", "HE1", "BED"],
            "Thermistors": ["T0", "T1", "TB"],
            "Expansion": ["CAN", "EXP1", "EXP2", "FAN0", "FAN1"],
        },
    ),
    "duet3_mini_5plus": BoardProfile(
        label="Duet 3 Mini 5+",
        mcu="samc21g18a",
        serial_hint="/dev/serial/by-id/usb-Duet3_Mini_5plus",
        pins={
            "stepper_x_step": "PA04",
            "stepper_x_dir": "PA05",
            "stepper_x_enable": "PA06",
            "stepper_y_step": "PA08",
            "stepper_y_dir": "PA09",
            "stepper_y_enable": "PA10",
            "stepper_z_step": "PB08",
            "stepper_z_dir": "PB09",
            "stepper_z_enable": "PB10",
            "extruder_step": "PB11",
            "extruder_dir": "PB12",
            "extruder_enable": "PB13",
            "heater_bed": "PA20",
            "heater_hotend": "PA21",
            "temp_bed": "PA03",
            "temp_hotend": "PA02",
            "probe": "PB02",
            "toolhead_fan": "PA16",
            "part_cooling_fan": "PA17",
            "filament_sensor": "PA18",
            "ams_step": "PB14",
            "ams_dir": "PB15",
            "ams_enable": "PA27",
        },
        layout={
            "Stepper Drivers": ["DRIVER0(X)", "DRIVER1(Y)", "DRIVER2(Z)", "DRIVER3(E0)", "DRIVER4(E1)"],
            "Heaters": ["HE0", "HE1", "BED"],
            "Thermistors": ["TEMP0", "TEMP1", "TEMPBED"],
            "Expansion": ["CAN-FD", "IO0", "IO1", "LCD", "PanelDue"],
        },
    ),
    "skr_pico": BoardProfile(
        label="BTT SKR Pico",
        mcu="rp2040",
        serial_hint="/dev/serial/by-id/usb-BTT_SKR_Pico",
        pins={
            "stepper_x_step": "GPIO11",
            "stepper_x_dir": "GPIO10",
            "stepper_x_enable": "GPIO12",
            "stepper_y_step": "GPIO6",
            "stepper_y_dir": "GPIO5",
            "stepper_y_enable": "GPIO7",
            "stepper_z_step": "GPIO19",
            "stepper_z_dir": "GPIO18",
            "stepper_z_enable": "GPIO20",
            "extruder_step": "GPIO14",
            "extruder_dir": "GPIO13",
            "extruder_enable": "GPIO15",
            "heater_bed": "GPIO23",
            "heater_hotend": "GPIO21",
            "temp_bed": "GPIO27",
            "temp_hotend": "GPIO26",
            "probe": "GPIO22",
            "toolhead_fan": "GPIO17",
            "part_cooling_fan": "GPIO16",
            "filament_sensor": "GPIO3",
            "ams_step": "GPIO2",
            "ams_dir": "GPIO1",
            "ams_enable": "GPIO0",
        },
        layout={
            "Stepper Drivers": ["X", "Y", "Z", "E0"],
            "Heaters": ["HE0", "BED"],
            "Thermistors": ["TH0", "THB"],
            "Expansion": ["CAN", "NeoPixel", "SPI", "GPIO"],
        },
    ),
    "skr_mini_e3_v3": BoardProfile(
        label="BTT SKR Mini E3 V3",
        mcu="stm32g0b1xx",
        serial_hint="/dev/serial/by-id/usb-BTT_SKR_Mini_E3_V3",
        pins={
            "stepper_x_step": "PB13",
            "stepper_x_dir": "PB12",
            "stepper_x_enable": "PB14",
            "stepper_y_step": "PB10",
            "stepper_y_dir": "PB2",
            "stepper_y_enable": "PB11",
            "stepper_z_step": "PB0",
            "stepper_z_dir": "PC5",
            "stepper_z_enable": "PB1",
            "extruder_step": "PB3",
            "extruder_dir": "PB4",
            "extruder_enable": "PD2",
            "heater_bed": "PC9",
            "heater_hotend": "PC8",
            "temp_bed": "PA2",
            "temp_hotend": "PA0",
            "probe": "PC14",
            "toolhead_fan": "PC7",
            "part_cooling_fan": "PC6",
            "filament_sensor": "PC15",
            "ams_step": "PA8",
            "ams_dir": "PA9",
            "ams_enable": "PA10",
        },
        layout={
            "Stepper Drivers": ["X", "Y", "Z", "E0"],
            "Heaters": ["HE0", "BED"],
            "Thermistors": ["TH0", "THB"],
            "Expansion": ["NeoPixel", "BLTouch", "TFT", "UART"],
        },
    ),
}


def get_board_profile(board_id: str) -> BoardProfile | None:
    return BOARD_REGISTRY.get(board_id)


def list_main_boards() -> list[str]:
    return sorted(BOARD_REGISTRY.keys())


TOOLHEAD_BOARD_REGISTRY: dict[str, BoardProfile] = {
    "btt_ebb36_v1_2": _toolhead_profile("BTT EBB36 v1.2", "stm32g0b1xx"),
    "btt_ebb42_v1_2": _toolhead_profile("BTT EBB42 v1.2", "stm32g0b1xx"),
    "btt_ebb_sb2209_2240": _toolhead_profile("BTT EBB SB2209/SB2240", "rp2040"),
    "btt_ebb2240_v1_0": _toolhead_profile("BTT EBB2240 v1.0", "rp2040"),
    "ldo_nitehawk_sb": _toolhead_profile("LDO Nitehawk SB", "rp2040"),
    "ldo_nitehawk_36": _toolhead_profile("LDO Nitehawk 36", "rp2040"),
    "mellow_fly_sht36_v2": _toolhead_profile("Mellow FLY-SHT36 v2", "stm32f072xb"),
    "mellow_fly_sht42_v2": _toolhead_profile("Mellow FLY-SHT42 v2", "stm32f072xb"),
    "fysetc_sb_can_2040": _toolhead_profile("FYSETC SB CAN 2040", "rp2040"),
}


def get_toolhead_board_profile(board_id: str) -> BoardProfile | None:
    return TOOLHEAD_BOARD_REGISTRY.get(board_id)


def list_toolhead_boards() -> list[str]:
    return sorted(TOOLHEAD_BOARD_REGISTRY.keys())
